import { initAuth, checkPassword, logout } from './core/auth.js';
import { loadData } from './core/data.js';
import { goBack } from './core/router.js';
import { openModal, closeModal } from './core/modal.js';
import { openCategory, openView, setSort } from './components/sales/sales.js';
import { openCustomersHub, openCustomersYear, openCustomersRolling, openCustomersView, setCustomersSort, openCustomerModal, closeCustomerModal } from './components/customers/customers.js';
import { openReturnsHub, openReturnsMonths, openReturnsPeriod, openReturnsProducts, openReturnsSuppliers, openReturnsIndicator, openReturnsSettlement } from './components/returns/returns.js';
import { openAlertsHub, openAlertsPeriod, filterAlertsBySupplier } from './components/alerts/alerts.js';
import { openFinanceHub, openFinanceSales, applyFinancePreset, applyFinanceCustomRange } from './components/finance/finance.js';
import { openCashflowHub, applyCashflowFilter, applyCashflowPickedWeek, applyCashflowOverrides } from './components/finance/cashflow.js';
import { openStockHub, showStockForDate, applyStockChartPeriod, toggleStockChartTable, toggleStockDateResults } from './components/stock/stock.js';
import { openSuppliersHub, openSuppliersRanking, openSupplierDetail, openSuppliersDemandHub, applySuppliersDemandPeriod } from './components/suppliers/suppliers.js';
import { openReorderHub, applyReorderFilter, openReorderProductModal } from './components/reorder/reorder.js';

window.checkPassword = checkPassword;
window.logout = logout;
window.loadData = loadData;
window.goBack = goBack;
window.openModal = openModal;
window.closeModal = closeModal;
window.openCategory = openCategory;
window.openView = openView;
window.setSort = setSort;
window.openCustomersHub = openCustomersHub;
window.openCustomersYear = openCustomersYear;
window.openCustomersRolling = openCustomersRolling;
window.openCustomersView = openCustomersView;
window.setCustomersSort = setCustomersSort;
window.openCustomerModal = openCustomerModal;
window.closeCustomerModal = closeCustomerModal;
window.openReturnsHub = openReturnsHub;
window.openReturnsMonths = openReturnsMonths;
window.openReturnsPeriod = openReturnsPeriod;
window.openReturnsProducts = openReturnsProducts;
window.openReturnsSuppliers = openReturnsSuppliers;
window.openReturnsIndicator = openReturnsIndicator;
window.openReturnsSettlement = openReturnsSettlement;
window.openAlertsHub = openAlertsHub;
window.openAlertsPeriod = openAlertsPeriod;
window.filterAlertsBySupplier = filterAlertsBySupplier;
window.openFinanceHub = openFinanceHub;
window.openFinanceSales = openFinanceSales;
window.applyFinancePreset = applyFinancePreset;
window.applyFinanceCustomRange = applyFinanceCustomRange;
window.openCashflowHub = openCashflowHub;
window.applyCashflowFilter = applyCashflowFilter;
window.applyCashflowPickedWeek = applyCashflowPickedWeek;
window.applyCashflowOverrides = applyCashflowOverrides;
window.openStockHub = openStockHub;
window.showStockForDate = showStockForDate;
window.applyStockChartPeriod = applyStockChartPeriod;
window.toggleStockChartTable = toggleStockChartTable;
window.toggleStockDateResults = toggleStockDateResults;
window.openSuppliersHub = openSuppliersHub;
window.openSuppliersRanking = openSuppliersRanking;
window.openSupplierDetail = openSupplierDetail;
window.openSuppliersDemandHub = openSuppliersDemandHub;
window.applySuppliersDemandPeriod = applySuppliersDemandPeriod;
window.openReorderHub = openReorderHub;
window.applyReorderFilter = applyReorderFilter;
window.openReorderProductModal = openReorderProductModal;

initAuth();
